apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    path: / 
    repoURL: 'http://localhost:8000' 
    targetRevision: HEAD
  project: default
